Convert OSM pbf file to osm rasters and roads csv
SpeciesConservationLandscapes/task_hii_osm_csv pull request #1
Opened 2021-03-29 17:50 UTC by gridcell

2021-03-29 17:57 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [OSM pipeline](https://trello.com/c/ka7OwdSB/29-osm-pipeline)

2021-03-29 19:20 UTC, saanobhaai requested changes
Just some minor comments...

2021-03-29 19:20 UTC, saanobhaai commented on README.md
>    -u OSM_URL, --osm_url OSM_URL
Should put `default` param on all args that then get documented here

2021-03-29 19:20 UTC, saanobhaai commented on src/config.py
> +road_tags = set((
Ideally this set of tags would only be specified once (i.e. combined with the set in the osmium config)

2021-03-29 19:20 UTC, saanobhaai commented on README.md
> +  a)Split up text file by attribute and tags and 1 million row CSV files
a) Split up text file into one CSV file per attribute/tag combination per 1 million rows

2021-03-29 19:20 UTC, saanobhaai commented on README.md
> +5. Merge all tiff into 1 multiband tiff file
well, it's 1 tiff split into global slices

2021-03-29 19:20 UTC, saanobhaai commented on src/task.py
> +    output_bounds = output_bounds or [-180.0, -90.0, 180.0, 90.0]
Is this why output footprints are the way we're seeing them in ee?

2021-03-29 19:20 UTC, saanobhaai commented on src/task.py
> +        self.max_rows = 1000000
Extract out of `__init__` as constant?

2021-03-29 19:20 UTC, saanobhaai commented on src/task.py
> +        if _extent:
Or maybe this test isn't behaving as expected? i.e. `argparse` is returning something truthy?

2021-03-29 19:20 UTC, saanobhaai commented on src/task.py
> +    parser.add_argument("--extent", type=str, help="Output geographic bounds.")
See earlier comments about defaults and also extent...

2021-03-30 07:51 UTC, saanobhaai requested changes
saw a typo, and still wondering about extent...

2021-03-30 07:51 UTC, saanobhaai commented on src/osmium_config.json
> +        "highway=bridleway": ["highway", "ridleway"],
Just noticed the tag typo... wonder if there's any way to check them all without doing it manually...

2021-03-30 07:51 UTC, saanobhaai commented on src/task.py
> +        default="-180.0,-58.0,180.0,84.0",
Couldn't this be `str(HIITask.extent)`?

2021-04-03 20:00 UTC, merged